### ISSUE TITLE
listEnrichrDbs() >>>>> Error in do.call

### ISSUE THREAD

**Issue by pbrazda** [wjawaid/enrichR#12] opened 2019-07-12 16:04 UTC
Hi All, 

After changing to 
` get(url = "https://amp.pharm.mssm.edu/Enrichr3/datasetStatistics")$content
`
I run into this error:

```
dbs <- listEnrichrDbs()
Error in do.call(cbind.data.frame, x) : second argument must be a list
Called from: do.call(cbind.data.frame, x)
Browse[1]>
```

Does anyone have any tips to follow from here?
Thanks!

**Comment by bblum9** [comment] 2019-07-12 19:27
Duplicate of #11

**Comment by pbrazda** [comment] 2019-07-12 20:30
I did the modification that was suggested in #11 .
now it's
```
> listEnrichrDbs
function() {
  dfSAF <- options()$stringsAsFactors
  options(stringsAsFactors = FALSE)
  dbs <- GET(url="http://amp.pharm.mssm.edu/Enrichr3/datasetStatistics")$content
  dbs <- intToUtf8(dbs)
  dbs <- fromJSON(dbs)
  dbs <- lapply(dbs$statistics, function(x) do.call(cbind.data.frame, x))
  dbs <- do.call(rbind.data.frame, dbs)
  options(stringsAsFactors = dfSAF)
  dbs
}
<bytecode: 0x7ff1c9ed82b0>
```
but after running it;
```
> dbs <- listEnrichrDbs()
Error in do.call(cbind.data.frame, x) : second argument must be a list
Called from: do.call(cbind.data.frame, x)
Browse[1]> 
```

**Comment by wjawaid** [comment] 2019-07-18 14:41
Problem isnow corrected with version 2
This is on GitHub and has been submitted to CRAN.
Thanks

**Closed by wjawaid** 2019-07-18 14:41 UTC
