### ISSUE TITLE
Results returning 'expired = true'

### ISSUE THREAD

**Issue by akv3001** [wjawaid/enrichR#13] opened 2019-07-12 17:08 UTC
Hi, when running enrichR our input lists are receiving this error. below 
{
"expired": true
}
On checking both links https://amp.pharm.mssm.edu/Enrichr/enrich
https://amp.pharm.mssm.edu/Enrichr3/enrich : this error was encountered.

We were wondering if this was an updated server issue or something else?

Thanks

**Comment by bblum9** [comment] 2019-07-12 19:27
Duplicate of #11

**Comment by schuti** [comment] 2019-07-14 02:17
Hi,
I run into the same issue ("expire":true) after the server updating (Enrichr to Enrichr3).
So I fixed it by replacing Enrichr with Enrichr3 in the URL of enrichr function and solved the issue.

Here is an example of the fixed enrichr function;

enrichr <- function(genes, databases = NULL) {
  cat("Uploading data to Enrichr... ")
  if (is.vector(genes) & ! all(genes == "") & length(genes) != 0) {
    temp <- POST(url="http://amp.pharm.mssm.edu/Enrichr3/enrich", **# replacing Enrichr with Enrichr3**
                 body=list(list=paste(genes, collapse="\n")))
  } else if (is.data.frame(genes)) {
    temp <- POST(url="http://amp.pharm.mssm.edu/Enrichr3/enrich", **# replacing Enrichr with Enrichr3**
                 body=list(list=paste(paste(genes[,1], genes[,2], sep=","),
                                      collapse="\n")))
  } else {
    warning("genes must be a non-empty vector of gene names or a dataframe with genes and score.")
  }
  GET(url="http://amp.pharm.mssm.edu/Enrichr3/share") **# replacing Enrichr with Enrichr3**
  cat("Done.\n")
  dbs <- as.list(databases)
  dfSAF <- options()$stringsAsFactors
  options(stringsAsFactors = FALSE)
  result <- lapply(dbs, function(x) {
    cat("  Querying ", x, "... ", sep="")
    r <- GET(url="http://amp.pharm.mssm.edu/Enrichr3/export", **# replacing Enrichr with Enrichr3**
             query=list(file="API", backgroundType=x))
    r <- gsub("&#39;", "'", intToUtf8(r$content))
    tc <- textConnection(r)
    r <- read.table(tc, sep = "\t", header = TRUE, quote = "", comment.char="")
    close(tc)
    cat("Done.\n")
    return(r)
  })
  options(stringsAsFactors = dfSAF)
  cat("Parsing results... ")
  names(result) <- dbs
  cat("Done.\n")
  return(result)
}

Thanks

**Comment by wjawaid** [comment] 2019-07-18 14:43
Hi
This was a problem with the EnrichR website.
It is now back online.
I have updated the enrichR package v2.0 so it gives more informative responses
Thanks

**Closed by wjawaid** 2019-07-18 14:43 UTC

**Comment by MikeDMorgan** [comment] 2021-02-20 23:40
Resurrecting this issue as enrichR currently returns `expired: true`.

**Comment by wjawaid** [comment] 2021-02-21 00:50
Have you updated to v3.0?
It uses the new website and is working on my system.

**Comment by MikeDMorgan** [comment] 2021-02-21 11:46
> Have you updated to v3.0?
> It uses the new website and is working on my system.

That fixed it - thanks for the quick response.

**Comment by HuynhNPT** [comment] 2021-02-25 14:23
I experienced the same issue with both enrichR v2 and v3. The following seems to fix it for now: 

```
dbs <- "GO_Biological_Process_2018"
options(enrichR.base.address="https://amp.pharm.mssm.edu/Enrichr/")
enrichr(genes = genes, databases = dbs)
```

**Comment by EnesSefaAyar** [comment] 2023-11-24 13:39
I have the same issue with "enrichR_3.2". It was OK yesterday, but currently function returns:

Code:
dbs <- c("WikiPathway_2023_Human", "GO_Biological_Process_2023", "KEGG_2021_Human")
enriched <- enrichr(res$To, dbs) # res$To is not empty
enriched


Console:

$WikiPathway_2023_Human
               X.
1 "expired": true
2               }

$GO_Biological_Process_2023
               X.
1 "expired": true
2               }

$KEGG_2021_Human
               X.
1 "expired": true
2               }

**Comment by vhaghani26** [comment] 2024-11-13 18:10
I am currently experiencing the same thing using GO_Biological_Process_2023, GO_Cellular_Component_2023, GO_Molecular_Function_2023, KEGG_2019_Mouse, Panther_2016, Reactome_2016, and RNA-Seq_Disease_Gene_and_Drug_Signatures_from_GEO. 

I tried yesterday and today, both times receiving the following output for every database:

X.
"expired": true
}

**Comment by yanningzuo** [comment] 2025-02-11 09:06
Hi, I am experiencing the same issue with enrichR_3.4 using the following databases: "KEGG_2021_Human", "GO_Biological_Process_2023", "BioCarta_2016", "Reactome_2022". Please help. Thank you!
